# Generated by Django 4.0.4 on 2022-06-25 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberprofile',
            name='name',
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
