# Generated by Django 4.0.4 on 2022-06-29 03:24

from django.db import migrations, models
import member.models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_memberprofile_payment_confirmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='practicing_certificate_picture',
            field=models.ImageField(blank=True, null=True, upload_to=member.models.upload_to),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='registration_certificate_picture',
            field=models.ImageField(blank=True, null=True, upload_to=member.models.upload_to),
        ),
    ]
