# Generated by Django 4.0.4 on 2022-07-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_memberprofile_practicing_certificate_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='member_registra_number',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
