# Generated by Django 4.0.4 on 2022-07-03 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_memberprofile_member_registra_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='member_number',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='member_registra_renewal',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
