# Generated by Django 4.0.4 on 2022-07-03 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_memberprofile_member_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='nationalID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
