# Generated by Django 4.0.4 on 2022-07-03 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_memberprofile_gender_memberprofile_nationalid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='dob',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
