# Generated by Django 4.0.4 on 2022-07-05 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_memberprofile_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='member_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='member_registra_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='member_registra_renewal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
